<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\LLRPReaderUI_Avalonia\Assets\rFid-icon.ico</ApplicationIcon>
    <VersionPrefix>1.0.13</VersionPrefix>
    <VersionSuffix>Alpha-260503</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LLRPReaderUI_Avalonia\LLRPReaderUI_Avalonia.csproj" />
  </ItemGroup>
</Project>
